### ISSUE TITLE
urls are being added to tweets

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-data-twitter#36]
details: https://rise-vision-inc.slack.com/archives/CCDCUDRJQ/p1589409508021100

**Comment by stulees** [comment]
@mmeiers @sheadarlison This has been fixed with https://github.com/Rise-Vision/twitter-service/pull/53 and deployed to production. To recap, quote tweets now have the shortened url (i.e. https://t.co/XXXX) removed. One thing to note - tweets get cached, so only tweets from this point forward will have the urls removed. Any tweets prior to the fix deployed today will continue to show the shortened url. Obviously as more tweets occur for the configured _username_ tweets, then these older cached tweets will eventually not be displayed, depending on the number of tweets in the queue the user has configured to show.
